plugins {
    id 'com.android.application'
}

android {
    namespace 'com.flyingmouse.format'
    compileSdk 36

    defaultConfig {
        applicationId "com.flyingmouse.format"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}
